### ISSUE TITLE
Migrate away from bower

### ISSUE THREAD

**Issue by mseshachalam** [purescript/documentation#257]
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by hdgarrood** [comment]
This has been discussed in numerous places already

**Comment by raym** [comment]
@hdgarrood can you provide a link to where this has been discussed?

As someone who would like to try PureScript, it is a giant red flag seeing bower used in the [Getting Started with PureScript](https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md) guide, which is the destination of the primary CTA on the homepage purescript.org.

Naturally I checked GitHub Issues because I was sure that someone would have brought it up. This issue has the most to-the-point title and shows up at the top. And then to see it closed like this with no link is frustrating.

I will push through and investigate how to use PureScript without Bower, but this current state of documentation must be discouraging to those who have heard great things about PureScript and want to give it a go.

That said, if I ever get the chance I will open a Pull Request about it.

**Comment by raym** [comment]
This looks like one of the discussions referenced:
https://github.com/purescript/documentation/issues/227#issuecomment-453798847

**Comment by JordanMartinez** [comment]
See a [short summary](https://github.com/JordanMartinez/purescript-jordans-reference/blob/ps-0.13.x-v0.18.2/02-Build-Tools/01-Dependency-Managers/01-Bower-Explained.md#why-doesnt-purescript-use-npm) of Harry's post explaining this in more depth: [Why the PureScript community uses Bower](https://harry.garrood.me/blog/purescript-why-bower/)
