### ISSUE TITLE
Merge getting-started guide with purescript book

### ISSUE THREAD

**Issue by milesfrain** [purescript/documentation#309]
How do we feel about merging the [getting-started guide in this repo](https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md) with the [getting started chapter in the book](https://book.purescript.org/chapter2.html)?

I'm hoping that deduplicating the guides will make maintenance easier and be better for new users.

If all content of this repo's guide is incorporated into the book, could we just redirect the "Quick Start Guide" link on [purescript.org](https://www.purescript.org/) to the book's chapter?

Wondering which example should be used. The Euler problem is more interesting, but the books diagonal function is simpler for beginners. Could also keep both examples.

**Comment by oldfartdeveloper** [comment]
I agree that the important task is to have only one "getting-started-guide" w/ no duplication in multiple places.

I'm slightly inclined to move the getting-started-guide into the purescript book and redirect the "Quick Start Guide".

In the getting-started-guide, I prefer using the "diagonal function" for the reason that I'm just trying to get the environment up and running; I don't care about interesting programs at that particular time.  The explanation of the generated Javascript is more cumbersome for the Euler exercise and I don't think the extra effort is appropriate in that place.

But since the Euler problem IS interesting, I'd like to see it drawn in to illustrate some aspect of Purescript that the book explains after the getting-started-guide.

Since I've already made some suggestions for the getting-started-guide (#324), I'm in this general area anyways and would be glad to follow up here by implementing this issue's objectives.

**Comment by milesfrain** [comment]
I agree with all your points.

Reasons for going with the current arrangement can be found in 
https://github.com/purescript-contrib/purescript-book/issues/93

We could always reconsider this decision though, although it's not the highest priority for me now that we accomplished the deduplication goals with merges in both repos.
